In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier

ModuleNotFoundError: No module named 'xgboost'

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# 103048 rows
''' not all the data are collected at the same intervals
for some datasets can merge, some cannot
'''

' not all the data are collected at the same intervals \nfor some datasets can merge, some cannot\n'

# Methods for loading/details of dataset

In [3]:
def load_data(name):
    path='drive/MyDrive/TeamProject/Data/'+name
    return pd.read_csv(path)

In [ ]:
def details(df):
    print('Column Types')
    print(df.dtypes)
    print('------------------')
    print('Missing Values')
    print(df.isna().sum())
    print('------------------')
    print('Description')
    print(df.describe().applymap('{:,.2f}'.format))

# Main Datasets

## ele.csv

In [ ]:
main_df=load_data('ele.csv')
main_df= main_df.drop('Unnamed: 6', axis=1)
main_df

                    date    mels_S     lig_S    mels_N     hvac_N     hvac_S
0          2018/1/1 1:00  1.200000  0.200000  7.500000  37.400002  19.500000
1          2018/1/1 1:15  1.300000  0.200000  6.800000  37.500000  19.889999
2          2018/1/1 1:30  1.100000  0.200000  7.400000  38.000000  19.299999
3          2018/1/1 1:45  1.200000  0.200000  7.700000  37.200001  18.889999
4          2018/1/1 2:00  1.100000  0.200000  7.300000  37.400002  24.700001
...                  ...       ...       ...       ...        ...        ...
103043  2020/12/31 23:00  0.071429  0.100000  1.177354   7.600000  27.652381
103044  2020/12/31 23:15  0.078571  0.100000  1.140462   7.461538  27.735000
103045  2020/12/31 23:30  0.093333  0.557143  1.792833   7.526000  27.022222
103046  2020/12/31 23:45  0.092308  0.680000  1.930493   7.851538  27.833333
103047     2021/1/1 0:00  0.107692  0.371429  1.000000   7.373333  29.843889

[103048 rows x 6 columns]

In [ ]:
details(main_df)

Column Types
date       object
mels_S    float64
lig_S     float64
mels_N    float64
hvac_N    float64
hvac_S    float64
dtype: object
------------------
Missing Values
date         0
mels_S      38
lig_S       34
mels_N      24
hvac_N    1542
hvac_S    1542
dtype: int64
------------------
Description
           mels_S       lig_S      mels_N      hvac_N      hvac_S
count  103,010.00  103,014.00  103,024.00  101,506.00  101,506.00
mean         2.57        1.46        8.75       21.23       19.72
std          2.57        1.86        6.44       14.56       12.88
min         -0.34       -0.05       -0.44        0.00        0.00
25%          0.60        0.10        2.61        8.45       10.45
50%          1.83        0.20        8.52       20.33       21.00
75%          3.00        3.40       10.85       32.12       26.68
max         14.58       10.71       35.98       84.50       79.80

replacing missing values with the value from previous rows

In [ ]:
main_df.fillna(method='ffill', inplace=True)
details(main_df)

Column Types
date       object
mels_S    float64
lig_S     float64
mels_N    float64
hvac_N    float64
hvac_S    float64
dtype: object
------------------
Missing Values
date      0
mels_S    0
lig_S     0
mels_N    0
hvac_N    0
hvac_S    0
dtype: int64
------------------
Description
           mels_S       lig_S      mels_N      hvac_N      hvac_S
count  103,048.00  103,048.00  103,048.00  103,048.00  103,048.00
mean         2.57        1.46        8.75       21.55       19.84
std          2.57        1.86        6.44       14.67       12.85
min         -0.34       -0.05       -0.44        0.00        0.00
25%          0.60        0.10        2.61        8.47       10.88
50%          1.83        0.20        8.52       20.55       21.00
75%          3.00        3.40       10.85       33.29       26.80
max         14.58       10.71       35.98       84.50       79.80

## site_weather.csv

In [ ]:
site_weather_df =load_data('site_weather.csv')
details(site_weather_df)
site_weather_df

Column Types
date                             object
air_temp_set_1                  float64
air_temp_set_2                  float64
dew_point_temperature_set_1d    float64
relative_humidity_set_1         float64
solar_radiation_set_1           float64
dtype: object
------------------
Missing Values
date                            0
air_temp_set_1                  0
air_temp_set_2                  0
dew_point_temperature_set_1d    0
relative_humidity_set_1         0
solar_radiation_set_1           0
dtype: int64
------------------
Description
      air_temp_set_1 air_temp_set_2 dew_point_temperature_set_1d  \
count     105,217.00     105,217.00                   105,217.00
mean           14.24          13.81                         6.86
std             5.22           4.78                         5.20
min             1.30           1.19                       -20.75
25%            10.64          10.56                         4.35
50%            13.18          12.87                         8.11
75%            17.10          16.33                        10.66
max            42.33          46.11                        18.92

      relative_humidity_set_1 solar_radiation_set_1
count              105,217.00            105,217.00
mean                    66.10                189.61
std                     21.63                275.33
min                      5.49                  0.00
25%                     51.17                  0.02
50%                     70.14                  5.01
75%                     85.00                342.50
max                     95.50              1,101.00

,date,air_temp_set_1,air_temp_set_2,dew_point_temperature_set_1d,relative_humidity_set_1,solar_radiation_set_1
0,2018-01-01 00:00:00,11.640,11.510,8.10,79.07,86.70
1,2018-01-01 00:15:00,11.490,11.420,8.14,80.10,45.88
2,2018-01-01 00:30:00,11.590,11.510,8.21,79.92,51.62
3,2018-01-01 00:45:00,11.440,11.410,8.11,80.20,21.43
4,2018-01-01 01:00:00,11.120,11.150,8.04,81.50,6.45
...,...,...,...,...,...,...
105212,2020-12-31 23:00:00,15.250,13.378,4.56,49.13,267.90
105213,2020-12-31 23:15:00,15.250,13.639,4.20,47.89,254.20
105214,2020-12-31 23:30:00,14.494,13.372,4.12,50.00,199.90
105215,2020-12-31 23:45:00,13.994,13.528,4.11,51.61,188.80
105216,2021-01-01 00:00:00,13.856,13.383,4.64,54.03,124.70

## Indoor Environmental Data

In [ ]:
cool_temp_zone_df =load_data('zone_temp_sp_c.csv')
details(cool_temp_zone)

Column Types
date                    object
zone_016_cooling_sp    float64
zone_017_cooling_sp    float64
zone_018_cooling_sp    float64
zone_019_cooling_sp    float64
zone_021_cooling_sp    float64
zone_023_cooling_sp    float64
zone_024_cooling_sp    float64
zone_025_cooling_sp    float64
zone_026_cooling_sp    float64
zone_027_cooling_sp    float64
zone_030_cooling_sp    float64
zone_032_cooling_sp    float64
zone_035_cooling_sp    float64
zone_036_cooling_sp    float64
zone_037_cooling_sp    float64
zone_038_cooling_sp    float64
zone_039_cooling_sp    float64
zone_041_cooling_sp    float64
zone_042_cooling_sp    float64
zone_043_cooling_sp    float64
zone_046_cooling_sp    float64
zone_047_cooling_sp    float64
zone_048_cooling_sp    float64
zone_049_cooling_sp    float64
zone_051_cooling_sp    float64
zone_053_cooling_sp    float64
zone_054_cooling_sp    float64
zone_055_cooling_sp    float64
zone_056_cooling_sp    float64
zone_057_cooling_sp    float64
zone_059_cooling_sp    float64
zone_061_cooling_sp    float64
zone_062_cooling_sp    float64
zone_063_cooling_sp    float64
zone_064_cooling_sp    float64
zone_065_cooling_sp    float64
zone_066_cooling_sp    float64
zone_067_cooling_sp    float64
zone_069_cooling_sp    float64
zone_070_cooling_sp    float64
zone_071_cooling_sp    float64
Unnamed: 42            float64
Unnamed: 43            float64
Unnamed: 44            float64
Unnamed: 45            float64
Unnamed: 46            float64
Unnamed: 47            float64
Unnamed: 48            float64
Unnamed: 49            float64
Unnamed: 50            float64
Unnamed: 51            float64
dtype: object
------------------
Missing Values
date                        0
zone_016_cooling_sp       501
zone_017_cooling_sp       499
zone_018_cooling_sp       499
zone_019_cooling_sp      1216
zone_021_cooling_sp       423
zone_023_cooling_sp       804
zone_024_cooling_sp       870
zone_025_cooling_sp       873
zone_026_cooling_sp       468
zone_027_cooling_sp       971
zone_030_cooling_sp       942
zone_032_cooling_sp       976
zone_035_cooling_sp       433
zone_036_cooling_sp       499
zone_037_cooling_sp       499
zone_038_cooling_sp      1107
zone_039_cooling_sp      1108
zone_041_cooling_sp         1
zone_042_cooling_sp       501
zone_043_cooling_sp       502
zone_046_cooling_sp       816
zone_047_cooling_sp       788
zone_048_cooling_sp       788
zone_049_cooling_sp      1136
zone_051_cooling_sp       288
zone_053_cooling_sp       956
zone_054_cooling_sp       504
zone_055_cooling_sp      1286
zone_056_cooling_sp      1284
zone_057_cooling_sp      1286
zone_059_cooling_sp      1292
zone_061_cooling_sp      1591
zone_062_cooling_sp         0
zone_063_cooling_sp       722
zone_064_cooling_sp       786
zone_065_cooling_sp       434
zone_066_cooling_sp      1217
zone_067_cooling_sp      1216
zone_069_cooling_sp       857
zone_070_cooling_sp     52574
zone_071_cooling_sp       860
Unnamed: 42            131725
Unnamed: 43            131725
Unnamed: 44            131725
Unnamed: 45            131725
Unnamed: 46            131725
Unnamed: 47            131725
Unnamed: 48            131725
Unnamed: 49            131725
Unnamed: 50            131725
Unnamed: 51            131725
dtype: int64
------------------
Description
      zone_016_cooling_sp zone_017_cooling_sp zone_018_cooling_sp  \
count          236,632.00          236,634.00          236,634.00
mean                75.12               75.12               75.40
std                  3.90                3.90                3.93
min                 73.00               73.00               73.00
25%                 73.00               73.00               73.00
50%                 74.00               74.00               74.00
75%                 74.00               74.00               75.00
max                 85.00               85.00               86.00

      zone_019_cooling_sp zone_021_cooling_sp zone_023_cooling_sp  \
count          235,917.00          236,710.00          236,329.00
mean                77.92               75.43               75.23
std                  0.27                4.20               17.83
min                 77.00               72.00               56.12
25%                 78.00               73.00               73.00
50%                 78.00               74.00               73.00
75%                 78.00               75.00               74.00
max                 79.25               86.00            6,091.47

      zone_024_cooling_sp zone_025_cooling_sp zone_026_cooling_sp  \
count          236,263.00          236,260.00          236,665.00
mean                74.83               75.11               74.74
std                  3.84                4.20                4.26
min                 72.11               72.00               71.44
25%                 73.00               73.00               73.00
50%                 73.00               74.00               73.00
75%                 74.00               74.00               74.00
max                 86.00               86.00               86.00

      zone_027_cooling_sp  ... Unnamed: 42 Unnamed: 43 Unnamed: 44  \
count          236,162.00  ...  105,408.00  105,408.00  105,408.00
mean                73.74  ...       75.32       73.83       74.59
std                  4.36  ...        2.56        2.44        2.46
min                 71.00  ...       74.00       73.00       73.58
25%                 71.00  ...       74.00       73.00       74.00
50%                 73.00  ...       75.00       73.00       74.00
75%                 74.00  ...       75.00       74.00       74.00
max                 85.00  ...       86.00       84.00       85.00

      Unnamed: 45 Unnamed: 46 Unnamed: 47 Unnamed: 48 Unnamed: 49 Unnamed: 50  \
count  105,408.00  105,408.00  105,408.00  105,408.00  105,408.00  105,408.00
mean        74.59       74.59       90.80       74.59       73.06       71.98
std          2.46        2.46      241.14        2.46        2.84        2.88
min         73.53       73.43      -58.93       73.58       71.50       70.77
25%         74.00       74.00       72.00       74.00       72.50       71.00
50%         74.00       74.00       72.00       74.00       72.50       71.00
75%         74.00       74.00       72.00       74.00       72.50       72.00
max         85.00       85.00   28,765.03       85.00       85.00       84.00

      Unnamed: 51
count  105,408.00
mean        75.27
std         22.89
min         52.59
25%         74.00
50%         74.00
75%         74.00
max      4,586.81

[8 rows x 51 columns]

In [ ]:
heat_temp_zone_df =load_data('zone_temp_sp_h.csv')
details(heat_temp_zone)

Column Types
date                    object
zone_016_heating_sp    float64
zone_017_heating_sp    float64
zone_018_heating_sp    float64
zone_019_heating_sp    float64
zone_021_heating_sp    float64
zone_023_heating_sp    float64
zone_024_heating_sp    float64
zone_025_heating_sp    float64
zone_026_heating_sp    float64
zone_027_heating_sp    float64
zone_030_heating_sp    float64
zone_032_heating_sp    float64
zone_035_heating_sp    float64
zone_036_heating_sp    float64
zone_037_heating_sp    float64
zone_038_heating_sp    float64
zone_039_heating_sp    float64
zone_041_heating_sp    float64
zone_042_heating_sp    float64
zone_043_heating_sp    float64
zone_046_heating_sp    float64
zone_047_heating_sp    float64
zone_048_heating_sp    float64
zone_049_heating_sp    float64
zone_051_heating_sp    float64
zone_053_heating_sp    float64
zone_054_heating_sp    float64
zone_055_heating_sp    float64
zone_056_heating_sp    float64
zone_057_heating_sp    float64
zone_059_heating_sp    float64
zone_061_heating_sp    float64
zone_062_heating_sp    float64
zone_063_heating_sp    float64
zone_064_heating_sp    float64
zone_065_heating_sp    float64
zone_066_heating_sp    float64
zone_067_heating_sp    float64
zone_069_heating_sp    float64
zone_070_heating_sp    float64
zone_071_heating_sp    float64
Unnamed: 42            float64
Unnamed: 43            float64
Unnamed: 44            float64
Unnamed: 45            float64
Unnamed: 46            float64
Unnamed: 47            float64
Unnamed: 48            float64
Unnamed: 49            float64
Unnamed: 50            float64
Unnamed: 51            float64
dtype: object
------------------
Missing Values
date                        0
zone_016_heating_sp       500
zone_017_heating_sp       500
zone_018_heating_sp       500
zone_019_heating_sp      1215
zone_021_heating_sp       422
zone_023_heating_sp       801
zone_024_heating_sp       870
zone_025_heating_sp       873
zone_026_heating_sp       468
zone_027_heating_sp       971
zone_030_heating_sp       943
zone_032_heating_sp      1333
zone_035_heating_sp       433
zone_036_heating_sp       497
zone_037_heating_sp       498
zone_038_heating_sp      1107
zone_039_heating_sp      1107
zone_041_heating_sp         1
zone_042_heating_sp       501
zone_043_heating_sp       501
zone_046_heating_sp       525
zone_047_heating_sp       500
zone_048_heating_sp       500
zone_049_heating_sp      1136
zone_051_heating_sp         1
zone_053_heating_sp       958
zone_054_heating_sp       504
zone_055_heating_sp      1287
zone_056_heating_sp      1285
zone_057_heating_sp      1285
zone_059_heating_sp      1291
zone_061_heating_sp      1591
zone_062_heating_sp         0
zone_063_heating_sp       433
zone_064_heating_sp       497
zone_065_heating_sp       434
zone_066_heating_sp      1216
zone_067_heating_sp      1214
zone_069_heating_sp       857
zone_070_heating_sp     52574
zone_071_heating_sp      1212
Unnamed: 42            131718
Unnamed: 43            131718
Unnamed: 44            131718
Unnamed: 45            131718
Unnamed: 46            131718
Unnamed: 47            131718
Unnamed: 48            131718
Unnamed: 49            131718
Unnamed: 50            131718
Unnamed: 51            131718
dtype: int64
------------------
Description
      zone_016_heating_sp zone_017_heating_sp zone_018_heating_sp  \
count          236,626.00          236,626.00          236,626.00
mean                69.02               69.02               69.30
std                  3.81                3.81                3.85
min                 59.00               59.00               59.00
25%                 70.00               70.00               70.00
50%                 70.00               70.00               71.00
75%                 71.00               71.00               71.00
max                 75.00               73.76               73.12

      zone_019_heating_sp zone_021_heating_sp zone_023_heating_sp  \
count          235,911.00          236,704.00          236,325.00
mean                63.92               69.33               69.01
std                  0.27                3.60               18.11
min                 62.80               59.00               20.19
25%                 64.00               70.00               70.00
50%                 64.00               71.00               70.00
75%                 64.00               71.00               71.00
max                 64.47               72.76            6,088.47

      zone_024_heating_sp zone_025_heating_sp zone_026_heating_sp  \
count          236,256.00          236,253.00          236,658.00
mean                68.72               69.01               68.64
std                  3.85                3.51                3.47
min                 58.88               60.00               59.00
25%                 70.00               70.00               70.00
50%                 70.00               70.00               70.00
75%                 70.00               71.00               70.00
max                 73.76               73.76               71.12

      zone_027_heating_sp  ... Unnamed: 42 Unnamed: 43 Unnamed: 44  \
count          236,155.00  ...  105,408.00  105,408.00  105,408.00
mean                68.63  ...       71.15       69.66       70.42
std                  3.85  ...        2.44        2.56        2.46
min                 59.00  ...       61.00       59.00       60.00
25%                 70.00  ...       71.00       70.00       71.00
50%                 70.00  ...       72.00       70.00       71.00
75%                 70.00  ...       72.00       70.00       71.00
max                 73.12  ...       72.98       74.00       74.00

      Unnamed: 45 Unnamed: 46 Unnamed: 47 Unnamed: 48 Unnamed: 49 Unnamed: 50  \
count  105,408.00  105,408.00  105,408.00  105,408.00  105,408.00  105,408.00
mean        70.42       70.42       80.67       70.42       70.31       69.70
std          2.46        2.46      240.97        2.46        2.46        2.57
min         60.00       60.00     -255.76       60.00       60.00       59.00
25%         71.00       71.00       69.00       71.00       71.00       70.00
50%         71.00       71.00       69.00       71.00       71.00       70.00
75%         71.00       71.00       69.00       71.00       71.00       71.00
max         74.00       74.00   28,762.03       74.00       74.00       72.98

      Unnamed: 51
count  105,408.00
mean        69.84
std         23.50
min         38.19
25%         71.00
50%         71.00
75%         71.00
max      4,583.81

[8 rows x 51 columns]

In [ ]:
zone_temp_interior_df =load_data('zone_temp_interior.csv')
details(zone_temp_interior_df)

Column Types
date                   object
cerc_templogger_1     float64
cerc_templogger_10    float64
cerc_templogger_11    float64
cerc_templogger_12    float64
cerc_templogger_13    float64
cerc_templogger_14    float64
cerc_templogger_15    float64
cerc_templogger_16    float64
cerc_templogger_2     float64
cerc_templogger_3     float64
cerc_templogger_4     float64
cerc_templogger_5     float64
cerc_templogger_6     float64
cerc_templogger_7     float64
cerc_templogger_8     float64
cerc_templogger_9     float64
dtype: object
------------------
Missing Values
date                      0
cerc_templogger_1      3930
cerc_templogger_10     7612
cerc_templogger_11      381
cerc_templogger_12    12253
cerc_templogger_13      999
cerc_templogger_14     1977
cerc_templogger_15    25242
cerc_templogger_16     6435
cerc_templogger_2       381
cerc_templogger_3      1668
cerc_templogger_4       381
cerc_templogger_5       381
cerc_templogger_6       383
cerc_templogger_7       381
cerc_templogger_8       380
cerc_templogger_9       383
dtype: int64
------------------
Description
      cerc_templogger_1 cerc_templogger_10 cerc_templogger_11  \
count        145,766.00         142,084.00         149,315.00
mean              23.24              24.19              23.75
std                1.43               0.97               1.16
min                0.00               0.00              19.12
25%               22.62              23.69              22.88
50%               23.31              24.25              23.75
75%               23.81              24.81              24.62
max               85.00              27.81              28.81

      cerc_templogger_12 cerc_templogger_13 cerc_templogger_14  \
count         137,443.00         148,697.00         147,719.00
mean               22.96              23.50              23.54
std                 1.14               0.97               0.95
min                18.31               0.00              18.56
25%                22.31              22.94              23.19
50%                23.00              23.69              23.69
75%                23.62              24.12              24.12
max                31.25              27.00              27.25

      cerc_templogger_15 cerc_templogger_16 cerc_templogger_2  \
count         124,454.00         143,261.00        149,315.00
mean               23.02              23.25             22.46
std                 6.36               1.03              0.90
min                 0.00              17.94             17.69
25%                22.94              22.88             21.94
50%                23.69              23.38             22.44
75%                24.50              23.88             22.94
max                85.00              85.00             26.53

      cerc_templogger_3 cerc_templogger_4 cerc_templogger_5 cerc_templogger_6  \
count        148,028.00        149,315.00        149,315.00        149,313.00
mean              24.30             23.36             23.21             23.73
std                1.12              0.76              1.12              1.06
min                0.00             19.94             19.31             18.56
25%               23.62             22.88             22.44             23.06
50%               24.31             23.31             23.00             23.94
75%               25.06             23.75             24.06             24.50
max               85.00             26.88             85.00             52.88

      cerc_templogger_7 cerc_templogger_8 cerc_templogger_9
count        149,315.00        149,316.00        149,313.00
mean              23.16             22.82             23.84
std                1.26              0.88              1.02
min               17.94             18.06             18.88
25%               22.44             22.50             23.19
50%               23.06             22.94             23.88
75%               24.12             23.38             24.50
max               27.06             25.50             27.62

## Setpoint Data

In [ ]:
rtu_sa_t_sp_df =load_data('rtu_sa_t_sp.csv')
details(rtu_sa_t_sp_df)

Column Types
date                  object
rtu_001_sat_sp_tn    float64
rtu_002_sat_sp_tn    float64
rtu_003_sat_sp_tn    float64
rtu_004_sat_sp_tn    float64
dtype: object
------------------
Missing Values
date                 0
rtu_001_sat_sp_tn    0
rtu_002_sat_sp_tn    0
rtu_003_sat_sp_tn    0
rtu_004_sat_sp_tn    0
dtype: int64
------------------
Description
      rtu_001_sat_sp_tn rtu_002_sat_sp_tn rtu_003_sat_sp_tn rtu_004_sat_sp_tn
count      1,578,292.00      1,578,292.00      1,578,292.00      1,578,292.00
mean              67.57             66.67             66.14             67.54
std                1.31              1.57              1.72              1.16
min               55.00             55.00             50.00             55.00
25%               67.75             65.00             65.00             67.63
50%               68.00             66.41             65.62             68.00
75%               68.00             68.00             68.00             68.00
max               72.00             72.00             72.00             72.00

In [ ]:
rtu_econ_sp_df =load_data('rtu_econ_sp.csv')
details(rtu_econ_sp_df)

Column Types
date                     object
rtu_001_econ_stpt_tn    float64
rtu_002_econ_stpt_tn    float64
rtu_003_econ_stpt_tn    float64
rtu_004_econ_stpt_tn    float64
dtype: object
------------------
Missing Values
date                    0
rtu_001_econ_stpt_tn    0
rtu_002_econ_stpt_tn    0
rtu_003_econ_stpt_tn    0
rtu_004_econ_stpt_tn    0
dtype: int64
------------------
Description
      rtu_001_econ_stpt_tn rtu_002_econ_stpt_tn rtu_003_econ_stpt_tn  \
count         1,384,223.00         1,384,223.00         1,384,223.00
mean                 67.56                66.70                66.20
std                   1.41                 1.70                 1.84
min                  55.00                55.00                50.00
25%                  68.00                65.00                64.00
50%                  68.00                68.00                66.00
75%                  68.00                68.00                68.00
max                  72.00                72.00                72.00

      rtu_004_econ_stpt_tn
count         1,384,223.00
mean                 67.54
std                   1.25
min                  55.00
25%                  68.00
50%                  68.00
75%                  68.00
max                  72.00

In [ ]:
rtu_sa_p_sp_df =load_data('rtu_sa_p_sp.csv')
details(rtu_sa_p_sp_df)

Column Types
date                          object
rtu_001_pa_static_stpt_tn    float64
rtu_002_pa_static_stpt_tn    float64
rtu_003_pa_static_stpt_tn    float64
rtu_004_pa_static_stpt_tn    float64
dtype: object
------------------
Missing Values
date                             0
rtu_001_pa_static_stpt_tn    11274
rtu_002_pa_static_stpt_tn     6680
rtu_003_pa_static_stpt_tn    11635
rtu_004_pa_static_stpt_tn    12286
dtype: int64
------------------
Description
      rtu_001_pa_static_stpt_tn rtu_002_pa_static_stpt_tn  \
count              1,396,026.00              1,400,620.00
mean                       0.06                      0.06
std                        0.00                      0.00
min                        0.06                      0.06
25%                        0.06                      0.06
50%                        0.06                      0.06
75%                        0.06                      0.06
max                        0.06                      0.06

      rtu_003_pa_static_stpt_tn rtu_004_pa_static_stpt_tn
count              1,395,665.00              1,395,014.00
mean                       0.22                      0.06
std                        0.25                      0.00
min                        0.06                      0.06
25%                        0.06                      0.06
50%                        0.06                      0.06
75%                        0.60                      0.06
max                        0.60                      0.06

In [ ]:
occ_df =load_data('occ.csv')
details(occ_df)

Column Types
date                 object
occ_third_south     float64
occ_fourth_south    float64
dtype: object
------------------
Missing Values
date                0
occ_third_south     0
occ_fourth_south    0
dtype: int64
------------------
Description
      occ_third_south occ_fourth_south
count      396,193.00       396,193.00
mean             6.59             4.85
std             11.03             8.31
min              0.00             0.00
25%              0.00             0.00
50%              1.00             1.00
75%              8.00             5.00
max             74.00            60.00

# Merging Datasets

# Data Cleaning

In [ ]:
drop_main_df= main_df.drop(['mels_S', 'mels_N', 'lig_S'], axis=1)

In [ ]:
drop_main_df

                    date     hvac_N     hvac_S
0          2018/1/1 1:00  37.400002  19.500000
1          2018/1/1 1:15  37.500000  19.889999
2          2018/1/1 1:30  38.000000  19.299999
3          2018/1/1 1:45  37.200001  18.889999
4          2018/1/1 2:00  37.400002  24.700001
...                  ...        ...        ...
103043  2020/12/31 23:00   7.600000  27.652381
103044  2020/12/31 23:15   7.461538  27.735000
103045  2020/12/31 23:30   7.526000  27.022222
103046  2020/12/31 23:45   7.851538  27.833333
103047     2021/1/1 0:00   7.373333  29.843889

[103048 rows x 3 columns]

In [ ]:
final_df=drop_main_df
final_df['average_energy_usage_data'] = final_df.mean(axis=1)
final_df

<ipython-input-65-60e42a39cfce>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  final_df['average_energy_usage_data'] = final_df.mean(axis=1)

                    date     hvac_N     hvac_S  average_energy_usage_data
0          2018/1/1 1:00  37.400002  19.500000                  28.450001
1          2018/1/1 1:15  37.500000  19.889999                  28.695000
2          2018/1/1 1:30  38.000000  19.299999                  28.650000
3          2018/1/1 1:45  37.200001  18.889999                  28.045000
4          2018/1/1 2:00  37.400002  24.700001                  31.050001
...                  ...        ...        ...                        ...
103043  2020/12/31 23:00   7.600000  27.652381                  17.626190
103044  2020/12/31 23:15   7.461538  27.735000                  17.598269
103045  2020/12/31 23:30   7.526000  27.022222                  17.274111
103046  2020/12/31 23:45   7.851538  27.833333                  17.842436
103047     2021/1/1 0:00   7.373333  29.843889                  18.608611

[103048 rows x 4 columns]

# Merge

In [ ]:
occ_df['date'] = pd.to_datetime(occ_df.date)
occ_df['date'] = occ_df['date'].dt.strftime("%y/%m/%d, %H:%M")
occ_df

                   date  occ_third_south  occ_fourth_south
0       18/05/22, 07:00              0.0               0.0
1       18/05/22, 07:01              0.0               1.0
2       18/05/22, 07:02              0.0               0.0
3       18/05/22, 07:03              0.0               1.0
4       18/05/22, 07:04              0.0               0.0
...                 ...              ...               ...
396188  19/02/21, 10:08              0.0               0.0
396189  19/02/21, 10:09              0.0               0.0
396190  19/02/21, 10:10              0.0               0.0
396191  19/02/21, 10:11              0.0               0.0
396192  19/02/21, 10:12              0.0               0.0

[396193 rows x 3 columns]

In [ ]:
rtu_sa_t_sp_df['date'] = pd.to_datetime(rtu_sa_t_sp_df.date)
rtu_sa_t_sp_df['date'] = rtu_sa_t_sp_df['date'].dt.strftime("%y/%m/%d, %H:%M")

,date,rtu_001_sat_sp_tn,rtu_002_sat_sp_tn,rtu_003_sat_sp_tn,rtu_004_sat_sp_tn
0,"18/01/01, 00:00",68.0,70.0,65.0,69.0
1,"18/01/01, 00:01",68.0,70.0,65.0,69.0
2,"18/01/01, 00:02",68.0,70.0,65.0,69.0
3,"18/01/01, 00:03",68.0,70.0,65.0,69.0
4,"18/01/01, 00:04",68.0,70.0,65.0,69.0
...,...,...,...,...,...
1578287,"20/12/31, 23:56",68.0,68.0,68.0,68.0
1578288,"20/12/31, 23:57",68.0,68.0,68.0,68.0
1578289,"20/12/31, 23:58",68.0,68.0,68.0,68.0
1578290,"20/12/31, 23:59",68.0,68.0,68.0,68.0
1578291,"21/01/01, 00:00",68.0,68.0,68.0,68.0

In [ ]:
rtu_econ_sp_df['date'] = pd.to_datetime(rtu_econ_sp_df.date)
rtu_econ_sp_df['date'] = rtu_econ_sp_df['date'].dt.strftime("%y/%m/%d, %H:%M")

In [ ]:
rtu_sa_p_sp_df['date'] = pd.to_datetime(rtu_sa_p_sp_df.date)
rtu_sa_p_sp_df['date'] = rtu_sa_p_sp_df['date'].dt.strftime("%y/%m/%d, %H:%M")

In [ ]:
final_df['date'] = pd.to_datetime(final_df.date)
final_df['date'] = final_df['date'].dt.strftime("%y/%m/%d, %H:%M")

In [ ]:
x =  pd.merge(final_df, rtu_sa_t_sp_df, rtu_sa_p_sp_df, rtu_econ_sp_df on="date")
y

,date,hvac_N,hvac_S,average_energy_usage_data,rtu_001_sat_sp_tn,rtu_002_sat_sp_tn,rtu_003_sat_sp_tn,rtu_004_sat_sp_tn
0,"18/01/01, 01:00",37.400002,19.500000,28.450001,68.0,70.0,65.0,69.0
1,"18/01/01, 01:15",37.500000,19.889999,28.695000,68.0,70.0,65.0,69.0
2,"18/01/01, 01:30",38.000000,19.299999,28.650000,68.0,70.0,65.0,69.0
3,"18/01/01, 01:45",37.200001,18.889999,28.045000,68.0,70.0,65.0,69.0
4,"18/01/01, 02:00",37.400002,24.700001,31.050001,68.0,70.0,65.0,69.0
...,...,...,...,...,...,...,...,...
103048,"20/12/31, 23:00",7.600000,27.652381,17.626190,68.0,68.0,68.0,68.0
103049,"20/12/31, 23:15",7.461538,27.735000,17.598269,68.0,68.0,68.0,68.0
103050,"20/12/31, 23:30",7.526000,27.022222,17.274111,68.0,68.0,68.0,68.0
103051,"20/12/31, 23:45",7.851538,27.833333,17.842436,68.0,68.0,68.0,68.0
103052,"21/01/01, 00:00",7.373333,29.843889,18.608611,68.0,68.0,68.0,68.0

In [ ]:
rtu_sa_t_sp_df

,date,rtu_001_sat_sp_tn,rtu_002_sat_sp_tn,rtu_003_sat_sp_tn,rtu_004_sat_sp_tn
0,2018-01-01 00:00:00,68.0,70.0,65.0,69.0
1,2018-01-01 00:01:00,68.0,70.0,65.0,69.0
2,2018-01-01 00:02:00,68.0,70.0,65.0,69.0
3,2018-01-01 00:03:00,68.0,70.0,65.0,69.0
4,2018-01-01 00:04:00,68.0,70.0,65.0,69.0
...,...,...,...,...,...
1578287,2020-12-31 23:56:00,68.0,68.0,68.0,68.0
1578288,2020-12-31 23:57:00,68.0,68.0,68.0,68.0
1578289,2020-12-31 23:58:00,68.0,68.0,68.0,68.0
1578290,2020-12-31 23:59:00,68.0,68.0,68.0,68.0
1578291,2021-01-01 00:00:00,68.0,68.0,68.0,68.0